### ISSUE TITLE
Encountering Error While Running Project

### ISSUE THREAD

**Issue by Smnrgcl** [octoposprime/op-be-gw#6]
```bash
go run cmd/service/main.go
```
I get this error when I run the project with this command.

```bash
runtime error: invalid memory address or nil pointer dereference

goroutine 9 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        C:/Program Files/Go/src/runtime/debug/stack.go:16 +0x13
github.com/99designs/gqlgen/graphql.DefaultRecover({0x0?, 0x0?}, {0x8cf480?, 0xfe4ac0?})
        {path}/go/pkg/mod/github.com/99designs/gqlgen@v0.17.43/graphql/recovery.go:17 +0x6b
github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x0?, {0xaaf758, 0xc00026a480}, {0x8cf480?, 0xfe4ac0?})       
        {path}/go/pkg/mod/github.com/99designs/gqlgen@v0.17.43/graphql/context_operation.go:124 +0x38
github.com/octoposprime/op-be-graphql/pkg/presentation/dto.(*executionContext)._Query_users.func1()
        {path}/github.com/op-be-graphql/pkg/presentation/dto/generated.go:2435 +0x6e
panic({0x8cf480?, 0xfe4ac0?})
        C:/Program Files/Go/src/runtime/panic.go:914 +0x21f
github.com/octoposprime/op-be-graphql/pkg/presentation/dto/model.(*UserDto).ToModel(0xc000274c50)
        {path}/github.com/op-be-graphql/pkg/presentation/dto/model/user.go:67 +0x18e
github.com/octoposprime/op-be-graphql/pkg/presentation/controller/graphql/resolver.(*queryResolver).Users(0xc000072cc8, {0xaaf758, 0xc00026a480}, 0xc000240240)
        {path}/github.com/op-be-graphql/pkg/presentation/controller/graphql/resolver/user.resolvers.go:159 +0x297
github.com/octoposprime/op-be-graphql/pkg/presentation/dto.(*executionContext)._Query_users.func2.1({0xaaf758?, 0xc00026a480})        {path}/github.com/op-be-graphql/pkg/presentation/dto/generated.go:2442 +0xc6
github.com/octoposprime/op-be-graphql/pkg/presentation/controller/graphql.(*Graphql).Auth(0xc000075cc0, {0xaaf758, 0xc000234f30}, {0xc000234f30?, 0x0?}, 0xc000244100, {0x9b52db, 0x9})
        {path}/github.com/op-be-graphql/pkg/presentation/controller/graphql/graphql.go:156 +0x41f
github.com/octoposprime/op-be-graphql/pkg/presentation/dto.(*executionContext)._Query_users.func2.2({0xaaf758, 0xc000234f30}) 
        {path}/github.com/op-be-graphql/pkg/presentation/dto/generated.go:2452 +0x84
github.com/octoposprime/op-be-graphql/pkg/presentation/dto.(*executionContext)._Query_users.func2({0xaaf758, 0xc000234f30})   
        {path}/github.com/op-be-graphql/pkg/presentation/dto/generated.go:2455 +0xd3
github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0xaaf758?, 0xc000234f30?}, 0xc0001bbce0?)
        {path}/go/pkg/mod/github.com/99designs/gqlgen@v0.17.43/graphql/executor/extensions.go:72 +0x22
github.com/octoposprime/op-be-graphql/pkg/presentation/dto.(*executionContext)._Query_users(0xc000244040, {0xaaf758, 0xc000234e10}, {0xc000240000, {0xc000244060, 0x2, 0x2}, 0x0})
        {path}/github.com/op-be-graphql/pkg/presentation/dto/generated.go:2439 +0x1ff        
github.com/octoposprime/op-be-graphql/pkg/presentation/dto.(*executionContext)._Query.func13({0xaaf758?, 0xc000234e10?}, 0xc000120500)
        {path}/github.com/op-be-graphql/pkg/presentation/dto/generated.go:6364 +0xa5
github.com/octoposprime/op-be-graphql/pkg/presentation/dto.(*executionContext)._Query.func14.1({0xaaf758?, 0xc000234e10?})    
        {path}/github.com/op-be-graphql/pkg/presentation/dto/generated.go:6373 +0x28
github.com/99designs/gqlgen/graphql/executor.processExtensions.func3({0xaaf758?, 0xc000234e10?}, 0x19febf43d10?)
        {path}/go/pkg/mod/github.com/99designs/gqlgen@v0.17.43/graphql/executor/extensions.go:69 +0x22
github.com/octoposprime/op-be-graphql/pkg/presentation/dto.(*executionContext)._Query.func14({0xaaf758, 0xc000234e10})        
        {path}/github.com/op-be-graphql/pkg/presentation/dto/generated.go:6372 +0xa2
github.com/octoposprime/op-be-graphql/pkg/presentation/dto.(*executionContext)._Query.func15({0x19fa6b90101?, 0x20?})
        {path}/github.com/op-be-graphql/pkg/presentation/dto/generated.go:6376 +0x22
github.com/99designs/gqlgen/graphql.(*FieldSet).Dispatch(0xc000120500, {0xaaf758?, 0xc000234db0?})
        {path}/go/pkg/mod/github.com/99designs/gqlgen@v0.17.43/graphql/fieldset.go:41 +0xa2
github.com/octoposprime/op-be-graphql/pkg/presentation/dto.(*executionContext)._Query(0xc000244040, {0xaaf758, 0xc000234d50}, 
{0xc0001fd0f0, 0x1, 0x1})
        {path}/github.com/op-be-graphql/pkg/presentation/dto/generated.go:6389 +0x1305       
github.com/octoposprime/op-be-graphql/pkg/presentation/dto.(*executableSchema).Exec.func1({0xaaf758, 0xc000234d20})
        {path}/github.com/op-be-graphql/pkg/presentation/dto/generated.go:599 +0x234
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1({0xaaf758, 0xc000234d20})
        {path}/go/pkg/mod/github.com/99designs/gqlgen@v0.17.43/graphql/executor/executor.go:120 +0x25
github.com/99designs/gqlgen/graphql/executor.processExtensions.func2({0xaaf758?, 0xc000234d20?}, 0x88a2e0?)
        {path}/go/pkg/mod/github.com/99designs/gqlgen@v0.17.43/graphql/executor/extensions.go:66 +0x22
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1({0xaaf758, 0xc000234c60})
        {path}/go/pkg/mod/github.com/99designs/gqlgen@v0.17.43/graphql/executor/executor.go:119 +0x104
github.com/99designs/gqlgen/graphql/handler/transport.POST.Do({0xaaf790?}, {0xaaeab0?, 0xc0001f42a0}, 0xc00016ed00, {0xaaeb70, 0xc0001ce6e0})
        {path}/go/pkg/mod/github.com/99designs/gqlgen@v0.17.43/graphql/handler/transport/http_post.go:91 +0x556       
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc000075d20, {0xaaeab0?, 0xc0001f42a0}, 0xc00016ed00)        
        {path}/go/pkg/mod/github.com/99designs/gqlgen@v0.17.43/graphql/handler/server.go:122 +0x278
github.com/octoposprime/op-be-graphql/pkg/presentation/controller/graphql.(*Graphql).Serve.corsMwHandler.func3({0xaaeab0, 0xc0001f42a0}, 0xc00016ec00)
        {path}/github.com/op-be-graphql/pkg/presentation/controller/graphql/graphql.go:95 +0x10d
net/http.HandlerFunc.ServeHTTP(0x10?, {0xaaeab0?, 0xc0001f42a0?}, 0xc00022a0ac?)
        C:/Program Files/Go/src/net/http/server.go:2136 +0x29
net/http.(*ServeMux).ServeHTTP(0x111205?, {0xaaeab0, 0xc0001f42a0}, 0xc00016ec00)
        C:/Program Files/Go/src/net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0xaad050?}, {0xaaeab0?, 0xc0001f42a0?}, 0x6?)
        C:/Program Files/Go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc00018fb90, {0xaaf758, 0xc0001fbe60})
        C:/Program Files/Go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 8
        C:/Program Files/Go/src/net/http/server.go:3086 +0x5cb
        ```

**Comment by Smnrgcl** [comment]
Hello,

The error encountered in the project is a runtime error in the form of "invalid memory address or nil pointer dereference". Upon investigating the source of this error, I noticed a nil pointer error in the github.com/octoposprime/op-be-graphql/pkg/presentation/dto/model.(*UserDto).ToModel function.

As a solution, necessary nil pointer checks were added in the (*UserDto).ToModel function, thus resolving the error. The changes were made in the relevant lines of the user.go file.

With these changes added, the function in question is now prevented from unexpectedly working with a nil object.

As seen, the solution to the error is quite simple, but I wanted to share this solution for the benefit of other developers who may encounter similar situations.

I have also included code snippets for detailed review.

**// Modified Code Sections**

```bash
func (u *UserDto) ToModel() *User {
    u.ModelData.UserBase = new(UserBase) // Initialize the UserBase field
    // Other code...
}
```
